import { writeFile, mkdir } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(__dirname, '..');

const BRANDS = ['carentan', 'railyard'];
const UPSTREAM = (brand) =>
  `https://raw.githubusercontent.com/marcinkwiatkowski605/Harbor-Token-System/main/dist/${brand}/tokens.css`;

async function syncBrand(brand) {
  const url = UPSTREAM(brand);
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Fetch ${url} failed: ${res.status}`);
  const raw = await res.text();

  const scoped = raw.replace(
    /:root(\s*\{)/,
    `[data-brand="${brand}"], :root[data-brand="${brand}"]$1`,
  );
  if (scoped === raw) {
    throw new Error(`Could not find :root selector in ${brand} tokens.css`);
  }

  const out = resolve(ROOT, 'src', 'tokens', brand, 'tokens.css');
  await mkdir(dirname(out), { recursive: true });
  const header = `/* Auto-generated by scripts/sync-tokens.mjs from ${url}\n   DO NOT EDIT — run \`npm run sync-tokens\` to refresh. */\n\n`;
  await writeFile(out, header + scoped, 'utf8');
  console.log(`✓ ${brand} → src/tokens/${brand}/tokens.css`);
}

await Promise.all(BRANDS.map(syncBrand));
